apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backend-ingress
spec:
  rules:
  - host: bold.servebeer.com
    http:
      paths:
      - path: /predict  # Only the /predict API route handled here
        pathType: Prefix
        backend:
          service:
            name: api-predict-service
            port:
              number: 80
